apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minio-deployment.yaml
- minio-pvc.yaml
- minio-service.yaml
<<<<<<< HEAD

secretGenerator:
- name: mlpipeline-minio-artifact
  envs: ["minio-artifact-secret.env"]
generatorOptions:
  # mlpipeline-minio-artifact needs to be referred by exact name
  disableNameSuffixHash: true
=======
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
