apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD
resources:
- metadata-grpc-configmap.yaml
- metadata-grpc-deployment.yaml
- metadata-grpc-service.yaml
- metadata-envoy-deployment.yaml
- metadata-envoy-service.yaml
images:
- name: gcr.io/ml-pipeline/metadata-envoy
  newTag: 1.0.0
=======

resources:
  - metadata-configmap.yaml
  - metadata-grpc-deployment.yaml
  - metadata-grpc-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
  - metadata-writer-deployment.yaml
  - metadata-writer-role.yaml
  - metadata-writer-rolebinding.yaml
  - metadata-writer-sa.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
