apiVersion: kustomize.config.k8s.io/v1beta1
<<<<<<< HEAD
kind: Kustomization
bases:
- ../../base
resources:
- application.yaml
commonLabels:
  app.kubernetes.io/name: aws-istio-authz-adaptor
  app.kubernetes.io/instance: aws-istio-authz-adaptor-0.1
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: aws-istio-authz-adaptor
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: "0.1"
=======
bases:
- ../../base
commonLabels:
  app.kubernetes.io/component: aws-istio-authz-adaptor
  app.kubernetes.io/name: aws-istio-authz-adaptor
kind: Kustomization
resources:
- application.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
