apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kf-admin-policy.yaml
- kf-admin-sa.yaml
- kf-user-policy.yaml
- kf-user-sa.yaml
<<<<<<< HEAD
- kf-admin-workload-identity-bindings.yaml
- kf-user-workload-identity-bindings.yaml
- admin-manages-user-policy.yaml
=======
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
