apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: minio
  app.kubernetes.io/name: minio
resources:
<<<<<<< HEAD
- ../generic
- persistent-volume.yaml
=======
- ../../../upstream/env/platform-agnostic/minio/
- ../../../upstream/base/argo/minio-artifact-secret.yaml # TODO: move it to minio/ folder
- persistent-volume.yaml
- ../../overlays/application/application.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
patchesStrategicMerge:
- persistent-volume-claim.yaml
configMapGenerator:
- name: pipeline-minio-install-config
  envs:
  - params.env
vars:
- name: kfpMinioPd
  objref:
    kind: ConfigMap
    name: pipeline-minio-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.minioPd
- name: kfpMinioPvName
  objref:
    kind: ConfigMap
    name: pipeline-minio-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.minioPvName
configurations:
- params.yaml
