apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: notebook-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: notebook-controller
<<<<<<< HEAD
      app.kubernetes.io/instance: notebook-controller-go-b0.0.2
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: notebook-controller-go
      app.kubernetes.io/part-of: hyperflow
      app.kubernetes.io/version: b0.0.2
=======
      app.kubernetes.io/instance: notebook-controller-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: notebook-controller
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment
    - group: core
      kind: ServiceAccount
  descriptor:
    type: notebook-controller
    version: v1beta1
    description: Notebooks controller allows users to create a custom resource \"Notebook\" (jupyter notebook).
    maintainers:
    - name: tmaxcloudck
      email: jeongwan_rho@tmax.co.kr
    owners:
    - name: Seungjin Lee
      email: seungjin_lee2@tmax.co.kr
    keywords:
     - jupyter
     - notebook
     - notebook-controller
     - jupyterhub
    links:
    - description: About
      url: "https://github.com/tmax-cloud/notebook-controller-go"
  addOwnerRef: true
